export const EDITOR_CONTENT_CSS = `
        .doc-tiptap-content{max-width:100%;box-sizing:border-box;overflow-x:auto;overflow-wrap:anywhere;word-break:break-word}.doc-tiptap-content p{margin:0 0 10px}.doc-tiptap-content h1{font-size:28px;line-height:1.45;margin:18px 0 12px;font-weight:700}.doc-tiptap-content h2{font-size:24px;line-height:1.45;margin:16px 0 10px;font-weight:700}.doc-tiptap-content h3{font-size:20px;line-height:1.5;margin:14px 0 8px;font-weight:650}.doc-tiptap-content h4,.doc-tiptap-content h5,.doc-tiptap-content h6{font-size:17px;line-height:1.55;margin:12px 0 8px;font-weight:650}.doc-tiptap-content>:first-child{margin-top:0}
        .doc-tiptap-content .doc-blockquote{border-left:3px solid #EBECF0;background:transparent;margin:6px 0;padding:2px 12px;color:#606266;border-radius:0}.doc-tiptap-content .doc-blockquote p{margin:0;line-height:1.8}.doc-tiptap-content .doc-blockquote p:last-child{margin-bottom:0}
        .doc-tiptap-content .doc-list{margin:8px 0 10px;padding-left:28px}.doc-tiptap-content .doc-ordered-list{list-style:decimal}.doc-tiptap-content .doc-ordered-list .doc-ordered-list{list-style:lower-alpha}.doc-tiptap-content .doc-ordered-list .doc-ordered-list .doc-ordered-list{list-style:lower-roman}.doc-tiptap-content .doc-bullet-list{list-style:disc}.doc-tiptap-content .doc-bullet-list .doc-bullet-list{list-style:circle}.doc-tiptap-content .doc-bullet-list .doc-bullet-list .doc-bullet-list{list-style:square}.doc-tiptap-content li{margin:4px 0;padding-left:2px}.doc-tiptap-content li>p{margin:0}.doc-tiptap-content .doc-task-list{list-style:none;margin:8px 0 10px;padding-left:0}.doc-tiptap-content .doc-task-item{display:flex;gap:8px;align-items:flex-start}.doc-tiptap-content .doc-task-item>label{margin-top:2px}.doc-tiptap-content .doc-task-item>div{flex:1}
        .doc-tiptap-content .doc-code-block-wrap{margin:16px 0;position:relative;border:1px solid #E8E9EE;border-radius:8px;background:#F6F7FA;overflow:hidden;display:flex;flex-direction:column;box-shadow:none}
        .doc-tiptap-content .doc-code-block-wrap.is-lang-open{overflow:visible;z-index:30}
        .doc-tiptap-content .doc-code-block{position:relative;background:#F6F7FA;border:0;border-radius:0;padding:16px;margin:0;font-family:PingFang SC,sans-serif;font-size:16px;line-height:26px;color:#3F4046;white-space:pre-wrap;box-sizing:border-box}
        .doc-tiptap-content .doc-code-block-wrap.is-plain-editing .doc-code-block{border-bottom:0}
        .doc-tiptap-content .doc-diagram.is-editing .doc-diagram-source{border-bottom:0}
        .doc-tiptap-content .doc-code-highlight{position:absolute;inset:0;padding:16px;margin:0;overflow:hidden;pointer-events:none;white-space:pre-wrap;word-break:break-word;font-family:PingFang SC,sans-serif;font-size:16px;line-height:26px;color:#3F4046;box-sizing:border-box;z-index:0}
        .doc-tiptap-content .doc-code-block>code{position:relative;z-index:1;display:block;background:transparent;outline:none;font-family:inherit;font-size:inherit;line-height:inherit;color:inherit}
        .doc-tiptap-content .doc-diagram{border:0;border-radius:0;background:#F6F7FA;overflow:visible;box-shadow:none}
        .doc-tiptap-content .doc-code-block-wrap.doc-diagram{border:1px solid #E8E9EE;border-radius:8px;overflow:hidden}
        .doc-tiptap-content .doc-code-block-wrap.doc-diagram.is-lang-open{overflow:visible}
        .doc-tiptap-content .doc-diagram.is-editing{display:flex;flex-direction:column;box-shadow:none}
        .doc-tiptap-content .doc-diagram-source-shell{display:grid;grid-template-rows:1fr;width:100%;flex-shrink:0;box-sizing:border-box;transition:grid-template-rows .28s ease}
        .doc-tiptap-content .doc-diagram-source-inner{min-height:0;overflow:hidden;display:flex;flex-direction:column}
        .doc-tiptap-content .doc-diagram.is-preview .doc-diagram-source-shell{grid-template-rows:0fr}
        .doc-tiptap-content .doc-diagram.is-editing .doc-diagram-source-shell{grid-template-rows:1fr}
        .doc-tiptap-content .doc-diagram .doc-diagram-source{margin:0;border:0;border-radius:0;background:#F6F7FA;padding:16px}
        .doc-tiptap-content .doc-diagram.is-editing .doc-diagram-source .doc-code-highlight{padding:16px}
        .doc-tiptap-content .doc-diagram.is-preview{cursor:pointer;background:#fff}
        .doc-tiptap-content .doc-diagram.is-preview:hover{border-color:#D8DAE0}
        .doc-tiptap-content .doc-diagram.is-editing .doc-diagram-preview{border-top:0;background:#fff;padding:16px;min-height:120px;border-radius:0 0 8px 8px}
        .doc-tiptap-content .doc-diagram.is-preview .doc-diagram-preview{padding:16px;min-height:120px}
        .doc-tiptap-content .doc-diagram-expand-bar{display:flex;align-items:center;justify-content:center;gap:6px;height:0;max-height:0;opacity:0;width:100%;padding:0 12px;margin:0;border:0;border-bottom:0 solid #E8E9EE;border-radius:0;background:#F6F7FA;color:#8D8E99;font-size:12px;font-family:PingFang SC,sans-serif;font-weight:400;line-height:1;cursor:pointer;flex-shrink:0;box-sizing:border-box;appearance:none;-webkit-appearance:none;overflow:hidden;pointer-events:none;transition:height .2s ease,max-height .2s ease,opacity .18s ease,border-bottom-width .2s ease}
        .doc-tiptap-content .doc-diagram.is-armed .doc-diagram-expand-bar{height:20px;max-height:20px;opacity:1;border-bottom-width:1px;pointer-events:auto}
        .doc-tiptap-content .doc-diagram.is-editing .doc-diagram-expand-bar{height:0;max-height:0;opacity:0;border-bottom-width:0;pointer-events:none}
        .doc-tiptap-content .doc-diagram-expand-bar:hover{background:#F5F6F8;color:#131212}
        .doc-tiptap-content .doc-diagram-expand-bar:active{background:#EBECF0;color:#131212}
        .doc-tiptap-content .doc-diagram-expand-label{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;max-width:70%}
        .doc-tiptap-content .doc-diagram-expand-chevron{width:0;height:0;border-left:4px solid transparent;border-right:4px solid transparent;border-top:5px solid currentColor;flex-shrink:0}
        @media (prefers-reduced-motion:reduce){.doc-tiptap-content .doc-diagram-expand-bar{transition:none!important}.doc-tiptap-content .doc-diagram-source-shell{transition:none!important}}
        .doc-tiptap-content .doc-diagram-preview{overflow-x:auto;text-align:center;box-sizing:border-box;color:#8D8E99;font-size:13px;font-family:PingFang SC,sans-serif;line-height:1.6;display:flex;align-items:center;justify-content:center}
        .doc-tiptap-content .doc-diagram-preview svg{max-width:100%;height:auto;display:block;margin:0 auto;pointer-events:none}
        .doc-tiptap-content .doc-diagram-error{color:#E53E3E;font-size:12px;line-height:1.5;text-align:left;white-space:pre-wrap;word-break:break-word;width:100%}
        .doc-tiptap-content .doc-code-delete-hint{display:none;position:absolute;top:16px;right:16px;z-index:4;width:44px;height:28px;padding:0;border-radius:4px;border:1px solid #E8E9EE;background:#fff;color:#131212;font-size:12px;font-family:PingFang SC,sans-serif;font-weight:400;line-height:1;cursor:pointer;align-items:center;justify-content:center;box-sizing:border-box}
        .doc-tiptap-content .doc-diagram.is-armed .doc-code-delete-hint{top:0;right:8px;height:20px;border:0;border-radius:0;background:transparent}
        .doc-tiptap-content .doc-code-delete-hint:hover{background:#F7F8FA}
        .doc-tiptap-content .doc-code-delete-hint:active{background:#EBECF0}
        .doc-tiptap-content .doc-code-actionbar{display:none;position:relative;z-index:6;align-items:center;justify-content:flex-end;gap:12px;height:64px;padding:0 16px;box-sizing:border-box;background:#fff;border-top:1px solid #E8E9EE;flex-shrink:0;border-radius:0;overflow:visible}
        .doc-tiptap-content .doc-code-block-wrap.is-plain-editing .doc-code-actionbar{display:flex!important;justify-content:flex-end;border-top:1px solid #E8E9EE;border-radius:0 0 8px 8px}
        .doc-tiptap-content .doc-diagram.is-editing .doc-code-actionbar{display:flex!important;justify-content:flex-end;border-top:1px solid #E8E9EE;border-bottom:1px solid #E8E9EE;border-radius:0}
        .doc-tiptap-content .doc-code-lang{display:none;align-items:center;justify-content:flex-end;padding:0;position:relative;z-index:8;overflow:visible}
        .doc-tiptap-content .doc-diagram.is-preview .doc-code-lang{display:none!important}
        .doc-tiptap-content .doc-code-actionbar .doc-code-lang{display:flex!important}
        .doc-tiptap-content .doc-code-lang-input,.doc-tiptap-content .doc-code-lang-trigger{width:120px;height:32px;padding:0 12px;border:1px solid #EBECF0;border-radius:8px;background:#fff;color:#131212;font-size:14px;font-family:PingFang SC,sans-serif;outline:none;box-sizing:border-box;text-align:center;letter-spacing:0.01em;transition:color .15s,background-color .15s,border-color .15s;cursor:pointer;pointer-events:auto;appearance:none;-webkit-appearance:none;display:inline-flex;align-items:center;justify-content:center;overflow:hidden;white-space:nowrap;text-overflow:ellipsis}
        .doc-tiptap-content .doc-code-lang-trigger.is-placeholder{color:#C0C4CC}
        .doc-tiptap-content .doc-code-lang-input:hover,.doc-tiptap-content .doc-code-lang-trigger:hover{background:#fff;color:#131212}
        .doc-tiptap-content .doc-code-lang-input:focus,.doc-tiptap-content .doc-code-lang-trigger:focus{border-color:#131212;box-shadow:none}
        .doc-tiptap-content .doc-code-lang-input::placeholder{color:#C0C4CC}
        /* 语言输入框/菜单挂在 document.body，不可加 .doc-tiptap-content 祖先选择器 */
        .doc-code-lang-portal{position:fixed;z-index:501;display:none;box-sizing:border-box}
        .doc-code-lang-portal .doc-code-lang-input{width:100%;height:100%;padding:0 12px;border:1px solid #131212;border-radius:8px;background:#fff;color:#131212;font-size:14px;font-family:PingFang SC,sans-serif;outline:none;box-sizing:border-box;text-align:center;letter-spacing:0.01em;cursor:text}
        .doc-code-lang-menu{position:fixed;z-index:502;width:168px;max-height:260px;display:flex;flex-direction:column;gap:0;overflow:hidden;background:#fff;border:1px solid #EBECF0;border-radius:8px;box-shadow:0 12px 24px -8px rgba(36,36,36,0.14);padding:4px;box-sizing:border-box}
        .doc-code-lang-list{flex:1;min-height:0;overflow:auto;display:flex;flex-direction:column;gap:0}
        .doc-code-lang-empty{height:32px;padding:0 12px;display:flex;align-items:center;font-size:13px;color:#8D8E99;font-family:PingFang SC,sans-serif}
        .doc-code-lang-item{height:30px;padding:0 10px;border-radius:6px;display:flex;align-items:center;font-size:12px;color:#131212;cursor:pointer;font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace;flex-shrink:0}
        .doc-code-lang-item:hover{background:#F7F8FA}
        .doc-code-lang-item.is-active{background:#EBECF0;font-weight:500}
        .doc-tiptap-content .hljs-keyword,.doc-tiptap-content .hljs-selector-tag{color:#0550ae}
        .doc-tiptap-content .hljs-string{color:#0a3069}
        .doc-tiptap-content .hljs-number{color:#0550ae}
        .doc-tiptap-content .hljs-comment{color:#8D8E99}
        .doc-tiptap-content .hljs-title,.doc-tiptap-content .hljs-section{color:#953800}
        .doc-tiptap-content .hljs-built_in{color:#0550ae}
        .doc-tiptap-content .doc-link{color:#134CFF;text-decoration:underline}.doc-tiptap-content .doc-image{display:block;max-width:100%;height:auto;margin:0;border-radius:8px;cursor:pointer}.doc-tiptap-content [data-resize-container][data-node="image"]{display:inline-flex;width:fit-content;margin:12px 6px;max-width:calc(100% - 12px);outline:none;position:relative;box-sizing:border-box;padding:4px}.doc-tiptap-content [data-resize-container][data-node="image"].ProseMirror-selectednode{outline:2px solid #134CFF;outline-offset:0;border-radius:8px}.doc-tiptap-content [data-resize-wrapper]{display:block;width:fit-content;max-width:100%;height:auto;line-height:0;position:relative;overflow:visible}.doc-tiptap-content [data-resize-handle]{background:#fff;border:2px solid #134CFF;border-radius:50%;box-sizing:border-box;height:12px;opacity:0;pointer-events:none;position:absolute;width:12px;z-index:3}.doc-tiptap-content [data-resize-container].ProseMirror-selectednode [data-resize-handle],.doc-tiptap-content [data-resize-container][data-resize-state="true"] [data-resize-handle]{opacity:1;pointer-events:auto}.doc-tiptap-content [data-resize-handle="top-left"]{cursor:nwse-resize;left:0;top:0;transform:translate(-50%,-50%)}.doc-tiptap-content [data-resize-handle="top-right"]{cursor:nesw-resize;right:0;top:0;transform:translate(50%,-50%)}.doc-tiptap-content [data-resize-handle="bottom-left"]{bottom:0;cursor:nesw-resize;left:0;transform:translate(-50%,50%)}.doc-tiptap-content [data-resize-handle="bottom-right"]{bottom:0;cursor:nwse-resize;right:0;transform:translate(50%,50%)}.doc-tiptap-content .doc-video{display:block;max-width:100%;margin:12px 0;border-radius:8px;background:#000}.doc-tiptap-content .doc-attachment{align-items:center;background:#f7f8fa;border:1px solid #ebecf0;border-radius:8px;color:#303133;display:flex;font-size:13px;margin:12px 0;max-width:520px;min-height:42px;padding:10px 12px;text-decoration:none}.doc-tiptap-content .doc-attachment:hover{border-color:#cfd4df;background:#f2f4f7}
        .doc-tiptap-content .tableWrapper{display:block;margin:14px 0;max-width:100%;overflow-x:auto;overflow-y:hidden;padding:2px 0 8px}.doc-tiptap-content .tableWrapper table,.doc-tiptap-content table.doc-table,.doc-tiptap-content table{border:1px solid #EEF0F5;border-collapse:collapse;border-spacing:0;display:table;margin:0;max-width:none;overflow:visible;table-layout:fixed;width:100%}.doc-tiptap-content table td,.doc-tiptap-content table th,.doc-tiptap-content .doc-table td,.doc-tiptap-content .doc-table th{border:1px solid #EEF0F5;box-sizing:border-box;min-width:96px;padding:7px 9px;position:relative;vertical-align:top}.doc-tiptap-content table th,.doc-tiptap-content .doc-table th{background:#f7f8fa;color:#131212;font-weight:600;text-align:left}.doc-tiptap-content table tr:nth-child(odd) td,.doc-tiptap-content .doc-table tr:nth-child(odd) td{background:rgba(238,240,245,0.502)}.doc-tiptap-content table td>*,.doc-tiptap-content table th>*,.doc-tiptap-content .doc-table td>*,.doc-tiptap-content .doc-table th>*{margin-bottom:0!important}.doc-tiptap-content table td p,.doc-tiptap-content table th p{line-height:1.6;margin:0;min-height:20px}.doc-tiptap-content table td p:empty::before,.doc-tiptap-content table th p:empty::before{content:"\\00a0";display:inline-block}.doc-tiptap-content table .selectedCell:after,.doc-tiptap-content .doc-table .selectedCell:after{background:rgba(19,76,255,0.12);content:"";inset:0;pointer-events:none;position:absolute;z-index:2}.doc-tiptap-content table td:focus-within,.doc-tiptap-content table th:focus-within,.doc-tiptap-content .doc-table td:focus-within,.doc-tiptap-content .doc-table th:focus-within{box-shadow:inset 0 0 0 2px rgba(0,94,255,0.18);background:#FAFCFF!important}.doc-tiptap-content .column-resize-handle{background:#134CFF;bottom:-2px;pointer-events:none;position:absolute;right:-3px;top:0;width:3px}.resize-cursor{cursor:col-resize}.table-row-resize-cursor,.table-row-resize-cursor *{cursor:row-resize!important}.doc-table-row-resize-handle{background:transparent;border-radius:0;cursor:row-resize;height:12px;position:fixed;touch-action:none;z-index:280}.doc-table-row-resize-handle::after{background:transparent;border-radius:999px;content:"";height:2px;left:0;position:absolute;right:0;top:5px;transition:background-color .12s ease}.doc-table-row-resize-handle:hover::after{background:rgba(19,76,255,0.18)}.doc-table-row-resize-handle.is-resizing::after{background:rgba(19,76,255,0.42)}
        .doc-tiptap-content .is-empty::before,.doc-tiptap-content .is-editor-empty::before{color:#b8bbc4;content:attr(data-placeholder);float:left;height:0;pointer-events:none}.doc-tiptap-content p.is-empty:first-child::before{color:#b8bbc4}.doc-tiptap-content pre.is-empty::before,.doc-tiptap-content .doc-code-block.is-empty::before,.doc-tiptap-content .doc-diagram-source.is-empty::before{content:none!important}.doc-tiptap-content:focus{outline:none}
        .doc-tiptap-content p[style*="text-align"],.doc-tiptap-content h1[style*="text-align"],.doc-tiptap-content h2[style*="text-align"],.doc-tiptap-content h3[style*="text-align"],.doc-tiptap-content h4[style*="text-align"],.doc-tiptap-content h5[style*="text-align"],.doc-tiptap-content h6[style*="text-align"]{display:block}
        .doc-table-float-bar{background:#FFFFFF!important}
        .doc-table-float-btn{height:28px;padding:0 8px;border-radius:8px;border:0;background:#FFFFFF;color:#131212;font-size:12px;font-family:PingFang SC,sans-serif;line-height:1;cursor:pointer;transition:background-color .15s;appearance:none;outline:none;white-space:nowrap}
        .doc-table-float-btn:hover{background:#EBECF0!important;border-radius:8px}
        .doc-table-float-btn.is-active{background:#EBECF0!important}
        .doc-table-float-btn.is-danger{background:#FFFFFF;color:#E53E3E}
        .doc-table-float-btn.is-danger:hover{background:#FFF1F0!important;border-radius:8px}
        .doc-table-float-label{height:28px;padding:0 8px;border-radius:8px;border:0;background:#FFFFFF;color:#8D8E99;font-size:12px;font-family:PingFang SC,sans-serif;display:inline-flex;align-items:center;user-select:none;white-space:nowrap}
        .doc-table-float-sep{width:1px;height:16px;background:#EBECF0;margin:0 2px;flex-shrink:0}
                .doc-editor-toolbar{position:relative;z-index:260;isolation:isolate;pointer-events:auto;scrollbar-gutter:stable both-edges;-webkit-overflow-scrolling:touch}
        .doc-editor-toolbar button,.doc-editor-toolbar [role="button"]{pointer-events:auto;position:relative;z-index:1}
        .doc-editor-toolbar button:hover{background-color:#EBECF0!important}
        .doc-editor-toolbar button:active{background-color:#EBECF0!important}
        /* macOS overlay 滚动条会压在内容右缘上抢点击：预留右侧安全区 + 非覆盖式滚动条 */
        .doc-editor-toolbar{padding-right:40px!important}
        .doc-editor-toolbar::-webkit-scrollbar{height:8px}
        .doc-editor-toolbar::-webkit-scrollbar-track{background:transparent}
        .doc-editor-toolbar::-webkit-scrollbar-thumb{background:rgba(0,0,0,0.18);border-radius:4px}
        .doc-editor-toolbar::-webkit-scrollbar-thumb:hover{background:rgba(0,0,0,0.32)}
      `;
