// @ts-nocheck — TipTap 多版本类型冲突（starter-kit 嵌套 @tiptap/core），运行时无问题

export type CodeBlockViewCtx = {
  node: any;
  editor: any;
  getPos: any;
  dom: HTMLDivElement;
  preview: HTMLDivElement;
  editHint: HTMLButtonElement;
  deleteHint: HTMLButtonElement;
  expandBar: HTMLButtonElement;
  expandBarLabel: HTMLSpanElement;
  expandBarChevron: HTMLSpanElement;
  sourceShell: HTMLDivElement;
  sourceInner: HTMLDivElement;
  actionBar: HTMLDivElement;
  pre: HTMLPreElement;
  code: HTMLElement;
  highlightLayer: HTMLDivElement;
  langBar: HTMLDivElement;
  langTrigger: HTMLButtonElement;
  currentNode: any;
  editing: boolean;
  armed: boolean;
  renderToken: number;
  lastSource: string;
  debounceTimer: number;
  selectionInside: boolean;
  editLockUntil: number;
  SOURCE_EXPAND_MS: number;
  sourceAnimToken: number;
  sourceAnimTimer: number;
  sourceCollapsing: boolean;
  sourceOpen: boolean;
  pendingFocusAfterExpand: boolean;
  blurCommitTimer: number;
  lockEnteringEdit: (extraMs?: number) => void;
  isEnteringEdit: () => boolean;
  prefersReducedMotion: () => boolean;
  afterPaint: (fn: () => void) => void;
  resetSourceShellStyle: () => void;
  stopSourceAnim: () => void;
  waitHeightTransition: (token: number, onDone: () => void) => void;
  finishExpandOpen: () => void;
  expandSourceShell: () => void;
  collapseSourceShell: (after: () => void) => void;
  isDiagram: () => boolean;
  isCommittedDiagram: () => boolean;
  diagramKind: () => ReturnType<typeof import("../../utils/diagrams").toDiagramKind>;
  langId: () => string;
  langPickerBusy: () => boolean;
  nodeRange: () => { pos: number; size: number } | null;
  readSource: () => string;
  focusAfterNode: () => void;
  selectionInThisBlock: () => boolean | null;
  rememberEditSession: () => void;
  clearEditSession: () => void;
  buildLangPickerSession: () => any;
  openLangPicker: () => void;
  syncLangPicker: () => void;
  syncHighlight: () => void;
  syncExpandBar: () => void;
  syncChrome: () => void;
  normalizePreviewSource: (source: string) => string;
  previewCacheKey: () => number | null;
  writePreviewCache: (source: string, html: string) => void;
  readPreviewCache: (source: string) => any;
  applyPreviewHtml: (html: string) => void;
  previewIsFresh: (source?: string) => boolean;
  restorePreviewFromCache: () => boolean;
  renderPreview: (source: string) => void;
  scheduleRender: () => void;
  placeCaretInSource: () => void;
  enterEdit: (opts?: { focusSource?: boolean }) => void;
  rememberArmedSession: () => void;
  clearArmedSession: () => void;
  armExpandBar: () => void;
  disarmExpandBar: () => void;
  commitEdit: (opts?: { keepSelection?: boolean }) => void;
  stopPointer: (event: Event) => void;
  onEnterPointer: (event: Event) => void;
  onExpandBarPointer: (event: Event) => void;
  deleteBlock: () => void;
  removeBlock: (event: Event) => void;
  onSelectionUpdate: () => void;
  onDocPointerDown: (event: Event) => void;
  onLangTriggerPointer: (event: Event) => void;
  onEditorBlur: () => void;
  editController: any;
};
